global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
    #추가
  - job_name: "mysql-metrics"
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: [ "mysql-exporter:9104" ]
